from __future__ import annotations
import json
from llmdiff.differ import DiffResult
from llmdiff.metrics import Summary


def _json_for_script(data: object) -> str:
    """Serialize data for safe embedding in an HTML <script> block.

    Escape HTML-significant characters so attacker-controlled text cannot
    terminate the script tag (for example via "</script>").
    """

    dumped = json.dumps(data, indent=2)
    return (
        dumped.replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    )


def render_html(results: list[DiffResult], summary: Summary) -> str:
    cases_json = _json_for_script(
        [
            {
                "id": r.case_id,
                "changed": r.changed,
                "similarity": (
                    round(r.similarity, 4) if r.similarity is not None else None
                ),
                "response_a": r.response_a,
                "response_b": r.response_b,
                "diff": r.unified_diff,
                "length_pct": r.structural_changes["length_pct"],
                "length_a": r.length_a,
                "length_b": r.length_b,
            }
            for r in results
        ],
    )

    summary_json = _json_for_script(
        {
            "total": summary.total,
            "changed": summary.changed,
            "unchanged": summary.unchanged,
            "avg_similarity": (
                round(summary.avg_similarity, 4)
                if summary.avg_similarity is not None
                else None
            ),
            "most_diverged": summary.most_diverged,
            "least_changed": summary.least_changed,
        },
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>llmdiff report</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; }}
  h1 {{ font-size: 20px; font-weight: 600; margin-bottom: 4px; }}
  .subtitle {{ color: #666; font-size: 14px; margin-bottom: 32px; }}
  .summary {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 32px; }}
  .metric {{ background: #f5f5f5; border-radius: 8px; padding: 12px 16px; }}
  .metric-num {{ font-size: 24px; font-weight: 600; }}
  .metric-lab {{ font-size: 12px; color: #666; margin-top: 2px; }}
  .case {{ border: 1px solid #e5e5e5; border-radius: 8px; margin-bottom: 16px; overflow: hidden; }}
  .case-header {{ display: flex; align-items: center; gap: 12px; padding: 12px 16px; background: #fafafa; border-bottom: 1px solid #e5e5e5; }}
  .case-id {{ font-weight: 600; font-size: 14px; }}
  .badge {{ font-size: 11px; font-weight: 600; padding: 2px 8px; border-radius: 4px; }}
  .changed {{ background: #fee2e2; color: #b91c1c; }}
  .unchanged {{ background: #dcfce7; color: #166534; }}
  .sim {{ font-size: 12px; color: #666; margin-left: auto; }}
  .responses {{ display: grid; grid-template-columns: 1fr 1fr; }}
  .resp {{ padding: 14px 16px; }}
  .resp:first-child {{ border-right: 1px solid #e5e5e5; }}
  .resp-label {{ font-size: 11px; font-weight: 600; color: #666; text-transform: uppercase; letter-spacing: .05em; margin-bottom: 8px; }}
  .resp-text {{ font-size: 13px; line-height: 1.6; white-space: pre-wrap; }}
  .diff-section {{ padding: 12px 16px; border-top: 1px solid #e5e5e5; background: #fafafa; }}
  .diff-label {{ font-size: 11px; font-weight: 600; color: #666; text-transform: uppercase; letter-spacing: .05em; margin-bottom: 8px; }}
  .diff-line {{ font-family: monospace; font-size: 12px; line-height: 1.6; }}
  .diff-add {{ background: #dcfce7; color: #166534; }}
  .diff-del {{ background: #fee2e2; color: #b91c1c; }}
  .diff-meta {{ color: #888; }}
</style>
</head>
<body>
<h1>llmdiff report</h1>
<div class="subtitle">Generated by <code>llmdiff</code></div>

<div id="root"></div>

<script>
const cases = {cases_json};
const summary = {summary_json};

function el(tag, cls, content) {{
  const e = document.createElement(tag);
  if (cls) e.className = cls;
  if (content) e.textContent = content;
  return e;
}}

// Summary
const summaryDiv = el('div', 'summary');
[
  [summary.total, 'Total cases'],
  [summary.changed, 'Changed'],
  [summary.unchanged, 'Unchanged'],
  [summary.avg_similarity !== null ? summary.avg_similarity.toFixed(2) : 'n/a', 'Avg similarity'],
].forEach(([num, label]) => {{
  const m = el('div', 'metric');
  m.appendChild(el('div', 'metric-num', String(num)));
  m.appendChild(el('div', 'metric-lab', label));
  summaryDiv.appendChild(m);
}});
document.getElementById('root').appendChild(summaryDiv);

// Cases
cases.forEach(c => {{
  const card = el('div', 'case');

  const header = el('div', 'case-header');
  header.appendChild(el('span', 'case-id', c.id));
  header.appendChild(el('span', 'badge ' + (c.changed ? 'changed' : 'unchanged'),
    c.changed ? 'CHANGED' : 'unchanged'));
  if (c.similarity !== null) {{
    header.appendChild(el('span', 'sim', `Similarity: ${{c.similarity.toFixed(2)}}`));
  }}
  card.appendChild(header);

  const resps = el('div', 'responses');
  ['a', 'b'].forEach(side => {{
    const r = el('div', 'resp');
    r.appendChild(el('div', 'resp-label', `Version ${{side.toUpperCase()}} · ${{side === 'a' ? c.length_a : c.length_b}} words`));
    r.appendChild(el('div', 'resp-text', side === 'a' ? c.response_a : c.response_b));
    resps.appendChild(r);
  }});
  card.appendChild(resps);

  if (c.diff && c.diff.length > 0) {{
    const ds = el('div', 'diff-section');
    ds.appendChild(el('div', 'diff-label', 'Diff'));
    c.diff.forEach(line => {{
      if (line.startsWith('+++') || line.startsWith('---')) return;
      const d = el('div', 'diff-line');
      d.textContent = line;
      if (line.startsWith('+')) d.className += ' diff-add';
      else if (line.startsWith('-')) d.className += ' diff-del';
      else if (line.startsWith('@@')) d.className += ' diff-meta';
      ds.appendChild(d);
    }});
    card.appendChild(ds);
  }}

  document.getElementById('root').appendChild(card);
}});
</script>
</body>
</html>"""
